title: Hun Chan Lee
logo: /images/headshot.png
google_scholar: "https://scholar.google.com/citations?user=LKxlknMAAAAJ&hl=en&oi=ao"
linkedin: "https://www.linkedin.com/in/hun-chan-lee-4b44288a"
cv_link: /docs/Hun Chan LeeCV.pdf
theme: jekyll-theme-minimal
