title: Hun Chan Lee
logo: /images/headshot.png
description: [Google Scholar](https://scholar.google.com/citations?user=LKxlknMAAAAJ&hl=en&oi=ao) | [Linkein](https://www.linkedin.com/in/hun-chan-lee-4b44288a)
theme: jekyll-theme-minimal
